### ISSUE TITLE
Logo not defined

### ISSUE THREAD

**Issue by ghost** [Druki-ru/website#69] opened 2021-05-24 13:58 UTC
Dear Developer!

receives the following error after installation:

```
На сайте произошла непредвиденная ошибка. Пожалуйста, повторите попытку позже.

Twig\Error\LoaderError: Template "/website/web/themes/custom/loremaster/logo.svg" is not defined. in Twig\Loader\ChainLoader->getSourceContext() (line 25 of themes/custom/loremaster/templates/content/block/block--system-branding-block.html.twig).
```

Regards,
The Lacesz

**Comment by Niklan** [comment] 2021-05-24 14:04
Do you have the same problem with standard installation under the same environment? I can't think of what can cause it, because is everything is default used for branding block. This is Drupal Core variable, no configuration changes, so I don't know even where to start looking for. It seems to be a misconfiguration of environment.

> "/website/web/themes/custom/loremaster/logo.svg"

This doesn't seem right. This should be `/web/themes/custom/loremaster/logo.svg. This 'website' prefix can be a problem, as I said earlier, this leads to your environment at this moment.

Btw. GitHub install website and open pages, so there is no such error.

**Comment by ghost** [comment] 2021-05-24 14:10
I use the default settings. I have not changed anything in the code. I downloaded the code from github today. If I disable the logo in the settings and add my own I get the following error:
```
На сайте произошла непредвиденная ошибка. Пожалуйста, повторите попытку позже.

Twig\Error\LoaderError: Template "/website/web/sites/default/files/gm-logo-100x100.png" is not defined. in Twig\Loader\ChainLoader->getSourceContext() (line 25 of themes/custom/loremaster/templates/content/block/block--system-branding-block.html.twig).
```
size does not matter. all sizes have the same error.

**Comment by Niklan** [comment] 2021-05-24 14:15
It's not about sizes, it's about environment. The path `/website/web/sites/default/files/gm-logo-100x100.png` should be `/web/sites/default/files/gm-logo-100x100.png`. The `/website` is not the part of the project, but the Drupal for some reason build URI with it, that's not right.

> I use the default settings.

I mean, if you install clean Drupal in that environment, do you have that problem or not? Because it seems to be your environment misconfiguration.

**Comment by ghost** [comment] 2021-05-24 15:07
no such problem with a clean installation.

**Comment by batkor** [comment] 2021-07-07 09:09
@thelacesz I now installed new project and works for me.
I think you need write your environment.
My env:
1. ArchLinux
2. Docker4Drupal

**Comment by chesn0k** [comment] 2021-07-07 11:15
@thelacesz Trying to reproduce the error you are facing, I installed webroot in the root of the project and got it ) You need to set webroot to `/web`, this should help.

If you tell us about your environment, we'll show you how do it.

**Comment by Niklan** [comment] 2021-09-23 11:02
I am closing this issue, if you still have questions open it or a new issue. Seems like this is an environment-specific problem.

**Closed as completed by Niklan** 2021-09-23 11:02 UTC
Labels: question
